apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-app
  name: frontend-app
  namespace: exam-46
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-app
    spec:
      containers:
      - image: asrorbekm/repo-2
        name: repo-2-container
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: info
              key: env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: info
              key: log_leveI
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: DB_URI
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: info
              key: grpc_port
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources: {}
status: {}
